#! /bin/bash

DIR="/tmp/highwaytest"
GPUID="0"
TYPE="highway"
DATASET="mnist"
SIZE="50"

mkdir -p "${DIR}"

for layers in 2 5 10 20 50 100
do
	th main.lua -gpuid 0 -cudnn 1 -mathematica "${DIR}/${TYPE}-${DATASET}-${layers}.m" -type "${TYPE}" -set "${DATASET}" -layers "${layers}" -size "${SIZE}" -max_epochs 400
done
