#! /bin/bash

DIR="results"
GPUID="1"
TYPE="highway"
DATASET="mnist"
DROPOUT="0.5"
SIZE="50"

mkdir -p "${DIR}"

for layers in 2 5 10 20 50 100
do
	th main.lua -gpuid "${GPUID}" -cudnn 1 -json "${DIR}/${TYPE}-${DATASET}-${layers}.json" -type "${TYPE}" -set "${DATASET}" -layers "${layers}" -dropout "${DROPOUT}" -size "${SIZE}" -max_epochs 400
done
