#! /bin/bash

DIR="results"
GPUID="0"
TYPE="vanilla"
DATASET="mnist"
SIZE="71"

mkdir -p "${DIR}"

for layers in 2 5 10 20 50 100
do
	th main.lua -gpuid "${GPUID}" -cudnn 1 -json "${DIR}/${TYPE}-${DATASET}-${layers}.json" -type "${TYPE}" -set "${DATASET}" -layers "${layers}" -size "${SIZE}" -max_epochs 400
done
